local Name, Private = ...
local E, L, V, P, G = unpack(ElvUI)

ProjectHopes.ChangelogTBL = {
	'v|cff99ff20250618|r 18/06/2025',
	' • Border for Aura indicators',
	' • Nil cleans for borders. .',
	' • Code cleanup.',
	' • 11.0.7 TOC update.',
' ',
	'v|cff99ff20250512|r 12/05/2025',
	' • Raid border now works for Raid 2+3',
	' • Minimap button fix, when changing spec.',
	' • Skin fixes.',
' ',
	'v|cff99ff20250423|r 23/04/2025',
	' • Fix Actionbar for Classic.',
	' • Patch bugs fixed.',
	' • BigWigs disabler weeee built in.',
' ',
	'v|cff99ff20250415|r 15/04/2025',
	' • Fix for Castbar when changing spec.',
	' • Better Targetglow',
' ',
	'v|cff99ff20250402|r 02/04/2025',
	' • FPS leak fix. . ',
	' • Better OMNICD skin. .',
	' • Fix for Castbar. ',
	' • Fix for automation tab. ',
' ',
	'v|cff99ff20250321|r 21/03/2025',
	' • Better Actionbar skinning. ',
	' • Better Minimap scaling.',
	' • Added My own touch on castbars.',
	' • Fix some minimap button not getting skinned.',
	' • Added DriveButton to minimap Buttons.',
	' • Removed unused libs.',
	' • Added new libs.',
	' • Fix Playerchoice skinning.',
	' • Fix Unitframe Glowline.',
' ',
	'v|cff99ff20250310|r 10/03/2025',
	' • New logo yea. ',
	' • Updated Plugin page to be better and stronger lol',
	' • Added Chat border on both side. ',
	' • Fixed Glowline to be better',
	' • Updated M+ dungoen teleports. ',
	' • Removed a taint from Classic (ElvUI recommend) ',
' ',
	'v|cff99ff20250304|r 04/03/2025',
	' • Skin fixes.',
	' • Raid and M+ Weakauras.',
	' • New Sounds.',
	' • New name tag.',
	' • TOC Update.',
' ',
	'v|cff99ff3320250226|r 26/02/2025',
	' • Added missing border on Friends frame, Classic.',
	' • Added Custom anchors.',
	' • Added skin for Nova World Buffs (Thanks Angelos).',
	' • Added skin for Nova Spell Ranker (Thanks Angelos).',
	' • Added skin for Open All (Thanks Angelos).',
	" • Added skin for What's Training (Thanks Angelos).",
	' • Added skin for Leatrix Plus (Thanks Angelos).',
	' • Added skin for Ranker (Thanks Angelos).',
	' • Fix some skin overlaps on wow classic (Thanks Angelos).',
	' • Fixed up Baganator skin.',
	' • Alot of changes to skinning config.',
	' • TOC Update.',
' ',
	'v|cff99ff3320250221|r 21/02/2025',
	' • Added debug mode.',
	' • Added 2 new commands, /projecthopesdebug on/off and /projecthopes to open config.',
	' • Fixed border issues on Class Trainer (Classic)',
	' • Fixed overlap of buttons on Gossip (Classic)',
	' • Fixed overlap of buttons on Merchant window (Classic)',
	' • Added missing border on profession "Unlean" button.',
	' • TOC Update.',
' ',
	'v|cff99ff3320250220|r 20/02/2025',
		' • Merchant expanded on classic.',
		' • Added skin for ThreatClassic2.',
		' • Added skin for Spy.',
		' • Added skin for DBM.',
		' • Added Health Glowline customization(Width and Custom Color)',
		' • Added new tag, "Hopes:perpp" it hides power number when 100 or 0.',
		' • TOC Update.',
	' ',
	'v|cff99ff3320250218|r 18/02/2025',
		' • Added this pretty changelog.',
		' • Removed Class icons and moved into ProjectHopes_Data.',
		' • Updated TOC on Classic and Era and Retail.',
		' • Cleaned up alot more code that is not used anymore.',
	' ',
		-- "• ''",
	-- ' ',
}

function ProjectHopes:LoadNewSettings()
	

	
	--- Keep this stuff ---
	Private:Print("New features is now set. Have fun!")
	E:StaticPopup_Show('ProjectHopes_RL')
end