local Name, Private = ...
local E, L, V, P, G = unpack(ElvUI)

ProjectHopes.ChangelogTBL = {
			'v|cff99ff20250930|r 30/09/2025',
	' • Added GameMenu way to open ProjectHopes.',
	' • Bugfix Raid frames can have multiple border enable.',
	' • Bugfix Raid LEFT_UP separator too long.',
	' • Bugfix Unitframe auras border not working.',
	' • Bugfix Opie skin not working properly.',
	' • Bugfix Great Vault typo.',
	' • Bugfix Alerts overlap.',
' ',
		'v|cff99ff20250927|r 27/09/2025',
	' • Added Great Vault info, found under Misc module.',
	' • Bugfix for Portraits being dumbdumb',
	' • Bugfix for Overshield being dumbdumb',
	' • Bugfix for WarpDeplete Skin being dumbdumb',
' ',
		'v|cff99ff20250926|r 26/09/2025',
	' • Added new module for Setting fonts, outline and statusbar.',
	' • Added new font.',
	' • Fix for /projecthopes to open config.',
	' • Revert background on raidframes.',
	' • Reworked OverShield module, to use ElvUIs own module for it, just changing texture.',
	' • Removed "Buffs and Debuffs" and moved em into ElvUI skinning instead.',
	' • Reconfig of Config files.',
	' • Fix for MinimapInstanceDifficulty that dont allow select font, align or Outline.',
	' • Cleanup in textures.',
	' • Fix for FrameMover not to being allowed to move all frames.',
	' • Fix Itemframe in Mists',
	' • TOC update to newest ElvUI version.',
' ',
	'v|cff99ff20250919|r 19/09/2025',
	' • Fixing better background to raidframes.',
	' • Fix for minimapbuttons.',
	' • Added skin for Opie.',
	' • Fix for border white on profie switch.',
	' • Fix for minimap moved 1 px down on profile switch.',
	' • Fix overlap of borders in LFG.',
' ',
	'v|cff99ff20250909|r 09/09/2025',
	' • Added missing border on RaidinfoFrame.',
	' • Fix for Extra Button border not anchoring..',
	' • Few new tags, info in ProjectHopes Tags tab. (Hopes:healerperpp, Hopes:roletext, Hopes:maxhealth:percent).',
	' • Completly rewritten Raidframes border and separator for all 3 raid for better anchoring and no bugs(I hope.).',
	' • Fix for MinimapInstanceDifficulty in Classic/Mists.',
	' • Fix for border on Petjournal.',
	' • Nil check on LootFrame.',
	' • Fix overlap in Iteminteraction.',
	' • Fix for border sometimes underneath cooldown swipe.',
	' • Added missing border on Macroframe.',
	' • Fix for LossControl frame.',
' ',
	'v|cff99ff20250826|r 26/08/2025',
	' • RaidFrame bug for somereason..',
	' • Completly new portraits module, alot of features.',
' ',
		'v|cff99ff20250816|r 16/08/2025',
	' • I keep forgetting this shit sorry.',
	' • Border fixes.',
	' • Reconfig DriveButton to be config for Cloak.',
	' • Fix for quick delete.',
' ',
	'v|cff99ff20250618|r 18/06/2025',
	' • Border for Aura indicators',
	' • Nil cleans for borders. .',
	' • Code cleanup.',
	' • 11.0.7 TOC update.',
' ',
	'v|cff99ff20250512|r 12/05/2025',
	' • Raid border now works for Raid 2+3',
	' • Minimap button fix, when changing spec.',
	' • Skin fixes.',
' ',
		-- "• ''",
	-- ' ',
}

function ProjectHopes:LoadNewSettings()


	--- Keep this stuff ---
	Private:Print("New features is now set. Have fun!")
	E:StaticPopup_Show('ProjectHopes_RL')
end